src/objects/Aircraft__c.object
<CustomObject>
    <fields>
        <fullName>Business_seats__c</fullName>
        <label>Business seats</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Economy_seats__c</fullName>
        <label>Economy seats</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Aircraft</label>
    <nameField>
        <label>Aircraft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flight_Info__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Id</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flight Infos</relationshipLabel>
        <relationshipName>Flight_Infos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_available_seats__c</fullName>
        <label>Business available seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_time_of_Flight__c</fullName>
        <label>Date time of Flight</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Economy_available_seats__c</fullName>
        <label>Economy available seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finish_flight_time__c</fullName>
        <label>Finish flight time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Flight Info</label>
    <nameField>
        <label>Flight Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FlightInfoTriggerHandler.cls
public with sharing class FlightInfoTriggerHandler {

    public static void handle(List<Flight_Info__c> newRecords, Map<Id, Flight_Info__c> oldMap, TriggerOperation operation) {
        switch on operation {
            when BEFORE_INSERT {
                checkSuccessAircraftFlightInfoTrigger(newRecords,oldMap);
                aircraftFlightInfoTrigger(newRecords, oldMap);
//                destinationAndDepartureFlightInfoTrigger(newRecords, oldMap);
            }
//            when BEFORE_UPDATE {
//                checkSuccessAircraftFlightInfoTrigger(newRecords,oldMap);
//                destinationAndDepartureFlightInfoTrigger(newRecords, oldMap);
//            }
        }
    }


    public static void aircraftFlightInfoTrigger(List<Flight_Info__c> newRecords, Map<Id, Flight_Info__c> oldMap) {
        Map<Id, Aircraft__c> aircraftMap = new Map<Id, Aircraft__c>();

        for (Flight_Info__c newFlightInfo : newRecords) {
            aircraftMap.put(newFlightInfo.AircraftId__c, null);
        }

        aircraftMap = new Map<Id, Aircraft__c>([
                SELECT Id,
                        Business_seats__c,
                        Economy_seats__c
                FROM Aircraft__c
                WHERE Id IN :aircraftMap.keySet()
        ]);
        for (Flight_Info__c seats : newRecords) {
            seats.Business_available_seats__c = aircraftMap.get(seats.AircraftId__c).Business_seats__c;
            seats.Economy_available_seats__c = aircraftMap.get(seats.AircraftId__c).Economy_seats__c;
        }
    }

    public static void checkSuccessAircraftFlightInfoTrigger(List<Flight_Info__c> newRecords, Map<Id, Flight_Info__c> oldMap) {
        List<Flight_Info__c> flightInfos = new List<Flight_Info__c>();
        flightInfos = new List<Flight_Info__c>([
                SELECT Id,
                        AircraftId__c,
                        Date_time_of_Flight__c,
                        Finish_flight_time__c
                FROM Flight_Info__c
        ]);

        for (Flight_Info__c newRec : newRecords) {
            for (Flight_Info__c anotherFI : flightInfos) {
                if (newRec.AircraftId__c == anotherFI.AircraftId__c &&
                        newRec.Date_time_of_Flight__c >= anotherFI.Date_time_of_Flight__c &&
                        newRec.Date_time_of_Flight__c <= anotherFI.Finish_flight_time__c  ||
                        newRec.AircraftId__c == anotherFI.AircraftId__c &&
                        newRec.Finish_flight_time__c >= anotherFI.Date_time_of_Flight__c &&
                        newRec.Finish_flight_time__c <= anotherFI.Finish_flight_time__c) {
                    newRec.AircraftId__c.addError('Aircraft for this time already used');
                }
            }
        }
    }
}