src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Traveled_miles__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Traveled miles</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Flight_Info__c.object
<CustomObject>
    <fields>
        <fullName>Business_available_seats__c</fullName>
        <label>Business available seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Economy_available_seats__c</fullName>
        <label>Economy available seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Flight_Distance__c</fullName>
        <label>Flight Distance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Flight Info</label>
    <nameField>
        <label>Flight Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Info_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flight Info Id</label>
        <referenceTo>Flight_Info__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Economy</fullName>
        <active>true</active>
        <label>Economy</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TicketTriggerHandler.cls
public with sharing class TicketTriggerHandler {

    public static void handle(List<Ticket__c> newRecords, Map<Id, Ticket__c> oldMap, TriggerOperation operation) {
        switch on operation {
            when BEFORE_INSERT {
                BookedBeforeTriggerTicket(newRecords);
                flightInfoTriggerTicket(newRecords, oldMap);
            }
            when BEFORE_UPDATE {
                flightInfoTriggerTicket(newRecords, oldMap);
            }
        }
    }

    public static void BookedBeforeTriggerTicket(List<Ticket__c> newRecords) {
        for (Ticket__c newTicket : newRecords) {
            newTicket.Status__c = 'Booked';
        }
    }

    public static void flightInfoTriggerTicket(List<Ticket__c> newRecords, Map<Id, Ticket__c> oldMap) {
        Map<Id, Contact> contactMap = new Map<Id, Contact>();

        System.debug('flightInfoTriggerTicket');
        for (Ticket__c newTicket : newRecords) {
            contactMap.put(newTicket.Contact__c, null);
        }

        contactMap = new Map<Id, Contact>([
                SELECT Id, Traveled_miles__c
                FROM Contact
                WHERE Id IN :contactMap.keySet()
        ]);

        Map<Id, Flight_Info__c> infoMap = new Map<Id, Flight_Info__c>();

        for (Ticket__c newFlightInfo : newRecords) {

            infoMap.put(newFlightInfo.Flight_Info_Id__c, null);
        }

        infoMap = new Map<Id, Flight_Info__c>([
                SELECT Id,
                        Flight_Distance__c,
                        Business_available_seats__c,
                        Economy_available_seats__c
                FROM Flight_Info__c
                WHERE Id IN :infoMap.keySet()
        ]);
        System.debug(infoMap);
        System.debug(contactMap);

        Map<Id, Schema.RecordTypeInfo> rtMap = Ticket__c.SObjectType.getDescribe().getRecordTypeInfosById();
        Boolean b;
        for (Ticket__c ticketBooked : newRecords) {
            if (oldMap != null && oldMap.containsKey(ticketBooked.Id) && oldMap.get(ticketBooked.Id).Status__c == 'Booked') {
                b = true;
            } else {
                b = false;
            }
            if (rtMap.get(ticketBooked.RecordTypeId).getDeveloperName().contains(Constants.BUSINESS_TYPE)) {
                if (infoMap.get(ticketBooked.Flight_Info_Id__c).Business_available_seats__c <= 0) {
                    ticketBooked.addError('This flight has not available seats in Business class');
                    System.debug('infoMap.get(ticketBooked.Flight_Info_Id__c).Business_available_seats__c <= 0');
                }
                if (ticketBooked.Status__c == 'Booked' && oldMap == null) {
                    infoMap.get(ticketBooked.Flight_Info_Id__c).Business_available_seats__c -= 1;
                    System.debug('ticketBooked.Status__c == \'Booked\' && oldMap == null');
                } else if (ticketBooked.Status__c == 'Returned' && contactMap != null && b == true) {
                    System.debug('ticketBooked.Status__c == \'Returned\' && contactMap != null');
                    infoMap.get(ticketBooked.Flight_Info_Id__c).Business_available_seats__c += 1;
                    ticketBooked.Contact__c = null;
                } else if (ticketBooked.Status__c == 'Completed' && contactMap != null && b == true) {
                    System.debug('ticketBooked.Status__c == \'Completed\' && contactMap != null');
                    contactMap.get(ticketBooked.Contact__c).Traveled_miles__c =
                            infoMap.get(ticketBooked.Flight_Info_Id__c).Flight_Distance__c * 0.3 +
                                    contactMap.get(ticketBooked.Contact__c).Traveled_miles__c;
                }


            } else if (rtMap.get(ticketBooked.RecordTypeId).getDeveloperName().contains(Constants.ECONOMY_TYPE)) {
                if (infoMap.get(ticketBooked.Flight_Info_Id__c).Economy_available_seats__c <= 0) {
                    System.debug('infoMap.get(ticketBooked.Flight_Info_Id__c).Economy_available_seats__c <= 0');
                    ticketBooked.addError('This flight has not available seats in Economy class');
                }
                if (ticketBooked.Status__c == 'Booked' && oldMap == null) {
                    System.debug('ticketBooked.Status__c == \'Booked\' && oldMap == null');
                    infoMap.get(ticketBooked.Flight_Info_Id__c).Economy_available_seats__c -= 1;
                } else if (ticketBooked.Status__c == 'Returned' && contactMap != null && b == true) {
                    System.debug('ticketBooked.Status__c == \'Returned\' && contactMap != null');
                    infoMap.get(ticketBooked.Flight_Info_Id__c).Economy_available_seats__c += 1;
                    ticketBooked.Contact__c = null;

                } else if (ticketBooked.Status__c == 'Completed' && contactMap != null && b == true) {
                    System.debug('ticketBooked.Status__c == \'Completed\' && contactMap != null');
                    contactMap.get(ticketBooked.Contact__c).Traveled_miles__c =
                            infoMap.get(ticketBooked.Flight_Info_Id__c).Flight_Distance__c * 0.1 +
                                    contactMap.get(ticketBooked.Contact__c).Traveled_miles__c;
                }
            }
        }
        update infoMap.values();
        update contactMap.values();
    }
}