src/objects/Flight_Info__c.object
<CustomObject>
    <fields>
        <fullName>Finish_flight_time__c</fullName>
        <label>Finish flight time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Flight Info</label>
    <nameField>
        <label>Flight Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Info_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flight Info Id</label>
        <referenceTo>Flight_Info__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MyBatchClass.cls
public with sharing class MyBatchClass implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Datetime dt = System.now();
        return Database.getQueryLocator(
        'SELECT Id,Status__c,Contact__c,Flight_Info_Id__r.Id,Flight_Info_Id__r.Finish_flight_time__c ' +
                'FROM Ticket__c ' +
                'WHERE Contact__c !=null AND ' +
                'Flight_Info_Id__r.Finish_flight_time__c > ' + dt.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\''));

    }
    public void execute(Database.BatchableContext bc, List<Ticket__c> records) {
        List<Ticket__c> tickets = new List<Ticket__c>();
            for (Ticket__c ti : records) {
                ti.Status__c = 'Completed';
                tickets.add(ti);
        }
        update tickets;
        System.debug(tickets);

    }
    public void finish(Database.BatchableContext bc) {
    }

}